Avoid using two periods in templates
Since $id_field already starts with a period, .$id_field would result in the
following in Go 1.5:

error: error parsing template {{range.items}}{{..metadata.name}}:{{end}}, template: output:1: unexpected . after term "."

Apparently, Go 1.4 allowed this. Unnecessary anyway.